import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Navbar from "../app/components/Navbar/Navbar"; // Adjusted import path
import LoadingScreen from "../app/components/LoadingScreen/LoadingScreen"; // Import LoadingScreen

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Vjcinfra",
  description: "Generated by Netzary",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={montserrat.className}>
        <LoadingScreen>  {/* ✅ Wrap everything with LoadingScreen */}
          <Navbar /> 
          {children}  
        </LoadingScreen>
      </body>
    </html>
  );
}
